### ISSUE TITLE
What version should I use?

### ISSUE THREAD

**Issue by nxtzbr** [espidev/ProtectionStones#105]
Hello, I would like to know what version I should use with my PaperSpigot 1.8.8 and WorldGuard 6.1?

**Comment by nxtzbr** [comment]
I'm getting a worldguard error (worldguard 6.1) :

[12:54:07 WARN]: [WorldGuard] An expected error occurred during a periodical save
java.lang.ClassCastException: java.lang.String cannot be cast to com.sk89q.worldguard.protection.flags.StateFlag$State
        at com.sk89q.worldguard.protection.flags.StateFlag.marshal(StateFlag.java:31) ~[worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.addMarshalledFlag(YamlRegionFile.java:312) ~[worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.getFlagData(YamlRegionFile.java:294) ~[worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.protection.managers.storage.file.YamlRegionFile.saveAll(YamlRegionFile.java:233) ~[worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.protection.managers.RegionManager.save(RegionManager.java:110) ~[worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.protection.managers.RegionManager.saveChanges(RegionManager.java:132) ~[worldguard-6.1.jar:6.1]
        at com.sk89q.worldguard.protection.managers.RegionContainerImpl$BackgroundSaver.run(RegionContainerImpl.java:232) [worldguard-6.1.jar:6.1]
        at java.util.TimerThread.mainLoop(Unknown Source) [?:1.8.0_101]
        at java.util.TimerThread.run(Unknown Source) [?:1.8.0_101]

**Comment by espidev** [comment]
I've never supported any version below 1.13, and WorldGuard 7. You have to use either KarenProtect, or the old Protectionsstones (before I maintained it) https://www.spigotmc.org/resources/protectionstones.10096/

**Comment by espidev** [comment]
inactive
