### ISSUE TITLE
Error occurred while enabling ProtectionStones v2.6.2 (Is it up to date?)

### ISSUE THREAD

**Issue by tads421** [espidev/ProtectionStones#116]
Good Evening, 

I am having an error when trying to load it with 1.14.4...

[18:03:45] [Server thread/ERROR]: Error occurred while enabling ProtectionStones v2.6.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at dev.espi.protectionstones.FlagHandler.registerHandlers(FlagHandler.java:91) ~[?:?]
        at dev.espi.protectionstones.ProtectionStones.onEnable(ProtectionStones.java:501) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:447) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:373) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:253) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:753) [craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[craftbukkit-1.14.4-R0.1-SNAPSHOT.jar:git-Bukkit-56118c6]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        ... 11 more

any idea why this would be?

Thanks
Kev

**Comment by espidev** [comment]
Are you using craftbukkit? Only Spigot and paperspigot is supported

**Comment by tads421** [comment]
Thank that was the issue! I was using craftbukkit
