### ISSUE TITLE
Place event

### ISSUE THREAD

**Issue by Haczyn** [espidev/ProtectionStones#139]
[17:53:44 ERROR]: Could not pass event BlockPlaceEvent to ProtectionStones v2.6.8
java.lang.NullPointerException: null
at dev.espi.protectionstones.utils.LimitUtil.hasPlayerPassedRegionLimit(LimitUtil.java:78) ~[?:?]
at dev.espi.protectionstones.utils.LimitUtil.check(LimitUtil.java:35) ~[?:?]
at dev.espi.protectionstones.BlockHandler.createPSRegion(BlockHandler.java:117) ~[?:?]
at dev.espi.protectionstones.BlockHandler.createPSRegion(BlockHandler.java:94) ~[?:?]
at dev.espi.protectionstones.ListenerClass.onBlockPlace(ListenerClass.java:72) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor564.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-103]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-103]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-103]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-103]
at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:333) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.ItemStack.placeItem(ItemStack.java:236) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:511) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1374) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1102) ~[patched_1.15.2.jar:git-Paper-103]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-103]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
My plugins Plugins (39): AntiXRay, AuctionHouse, AuthMe, AutoMessage, BetterRTP*, ChestCommands, ChestShop, ClearLag, CombatLogX, CommandButtons, dynmap*, EasySetSpawn*, EntityTrackerFixer, Essentials, EssentialsChat, EssentialsProtect, FarmLimiter, ForcedGrammar*, HolographicDisplays, IllegalStack, Jobs, KeepDeathDrop, LimitPillagers, LogBlock, MobArena, Multiverse-Core, PermissionsEx*, ProtectionStones, ScoreboardStats*, Shopkeepers, SkinsRestorer, TabList, Vault, VillagerOptimiser, Voting*, WorldBorder, WorldEdit, WorldGuard, WorldGuardExtraFlags 
1.15.2

**Comment by espidev** [comment]
What are the worlds that you have on the server? Do you have custom worlds, or ones that are disabled with multiverse?

**Comment by Haczyn** [comment]
I have just custom world where is nobody. Protectionstone get crashed place event since 1d. Idk why, before on that version everything was okay. When i put plot as OP in console its that event but it create plot. when player put block with plot it doesnt work. Before was everything okey

**Comment by Haczyn** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/60531623/74469444-f32e8b80-4e9c-11ea-8483-bad63c4cb6c1.jpg)
Before nothing i have server since 4month

**Comment by espidev** [comment]
Okay, so this is actually just a simple null check I can add.
Perhaps some world that you have is not loaded by WorldGuard, or is disabled?

Anyway, I'll add a fix in for the next version

```

    /**
     * Get the region manager for a world if one exists.
     *
     * <p>If you wish to make queries and performance is more important
     * than accuracy, use {@link #createQuery()} instead.</p>
     *
     * <p>This method may return {@code null} if region data for the given
     * world has not been loaded, has failed to load, or support for regions
     * has been disabled.</p>
     *
     * @param world the world
     * @return a region manager, or {@code null} if one is not available
     */
    @Nullable
    public RegionManager get(World world) {
        return container.get(world.getName());
    }

```

**Comment by espidev** [comment]
oops ignore that close

**Comment by Haczyn** [comment]
custom world is disabled and not used just for admins. I back to 2.6.4 vesrion to fix that error. and now it work

**Comment by espidev** [comment]
Oh, huh

Okay, I'll push out a test build with fixes once I'm done, and let me know if it fixes the issue.

**Comment by Haczyn** [comment]
Btw i back to 2.6.6 and it worked a few minutes and again crash fk okey where i will find test build?

**Comment by espidev** [comment]
Please give this build a try: https://ci.espi.dev/job/ProtectionStones/229/artifact/target/protectionstones-2.6.8.jar

**Comment by espidev** [comment]
Will make its way into 2.6.9
