### ISSUE TITLE
Non-working plugin even though I meet the conditions

### ISSUE THREAD

**Issue by OlekMK342** [espidev/ProtectionStones#144]
Hey, I'm doing a survival server and I have uploaded your plugin, I have "WorldEdit 7.1.0", "WorldGuard 7.0.2", "Vault", "WorldGuardExtraFlags" installed and the plugin still does not work, when entering "/ pl" the plugin is displayed and works, but the commands and the plugins folder itself do not appear/work.
I thought that maybe I need to install the old version of the plugin but it does not work, so I decided that I would write to you because I was thinking for a long time what to do :(

Yes, I used google translate ._.

**Comment by espidev** [comment]
Do you have any error logs? Are there ProtectionStones logs when the server starts up? Which server version are you using? Are you able to do /ps and /wg?

**Comment by espidev** [comment]
You can hop on to the MOSS discord if you want

**Comment by OlekMK342** [comment]
1. Yes, Could not pass event PlayerJoinEvent to ProtectionStones v2.6.9
org.bukkit.event.EventException: null
2. No
3. 1.15.2
4. /ps no, but /wg yes

I installed v2.0.0 and it works, but rather blocks from 1.15 will not work ._.

**Comment by OlekMK342** [comment]
Caused by: java.lang.NullPointerException
at dev.espi.protectionstones.ListenerClass.onPlayerJoin(ListenerClass.java:65) ~[?:?]

[Server thread/INFO]: [ProtectionStones] Disabling ProtectionStones v2.6.9

**Comment by espidev** [comment]
Are you sure that in the logs there isn't  saying something to the effect of "Enabling Protectionstones"?

It's strange that the plugin would disable. Is the player joining before the server started up?

So only 1.15 blocks don't work as ProtectionStones for you, right?

**Comment by OlekMK342** [comment]
You are right in the journal is what you wrote:
[00:53:08] [Server thread/INFO]: [ProtectionStones] Enabling ProtectionStones v2.6.9
[00:53:08] [Server thread/INFO]: [WorldGuard] Registering session handler dev.espi.protectionstones.flags.GreetingFlagHandler
[00:53:08] [Server thread/INFO]: [WorldGuard] Registering session handler dev.espi.protectionstones.flags.FarewellFlagHandler
[00:53:09] [Server thread/INFO]: PlaceholderAPI support enabled!
[00:53:09] [Server thread/ERROR]: Error occurred while enabling ProtectionStones v2.6.9 (Is it up to date?)
java.lang.IllegalArgumentException: Recipe must have non-AIR result.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.inventory.ShapedRecipe.(ShapedRecipe.java:45) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]

2. No, nobody entered before turning on or reloading
3. All versions of this plugin do not work if they are above 2.0.0

**Comment by OlekMK342** [comment]
More information from the console if it helps you:

[00:53:08] [Server thread/INFO]: [ProtectionStones] Enabling ProtectionStones v2.6.9
[00:53:08] [Server thread/INFO]: [WorldGuard] Registering session handler dev.espi.protectionstones.flags.GreetingFlagHandler
[00:53:08] [Server thread/INFO]: [WorldGuard] Registering session handler dev.espi.protectionstones.flags.FarewellFlagHandler
[00:53:09] [Server thread/INFO]: PlaceholderAPI support enabled!
[00:53:09] [Server thread/ERROR]: Error occurred while enabling ProtectionStones v2.6.9 (Is it up to date?)
java.lang.IllegalArgumentException: Recipe must have non-AIR result.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.inventory.ShapedRecipe.(ShapedRecipe.java:45) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftShapedRecipe.(CraftShapedRecipe.java:19) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.craftbukkit.v1_15_R1.inventory.CraftShapedRecipe.(CraftShapedRecipe.java:23) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:46) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.ShapedRecipes.toBukkitRecipe(ShapedRecipes.java:1) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.craftbukkit.v1_15_R1.inventory.RecipeIterator.next(RecipeIterator.java:31) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.craftbukkit.v1_15_R1.inventory.RecipeIterator.next(RecipeIterator.java:1) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at dev.espi.protectionstones.PSConfig.removePSRecipes(PSConfig.java:239) ~[?:?]
at dev.espi.protectionstones.ProtectionStones.loadConfig(ProtectionStones.java:394) ~[?:?]
at dev.espi.protectionstones.ProtectionStones.onEnable(ProtectionStones.java:484) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]

**Comment by espidev** [comment]
Something is wrong with your config, relating to your crafting recipe.

**Comment by OlekMK342** [comment]
Wait, I don't understand, no "ProtectionStones" folder is being created, where should I find it? It's somewhere in the plugins folder?

I am sorry for not embracing me in the country is 2 AM
Anyway, thanks for helping

**Comment by OlekMK342** [comment]
Is there any chance that the recipes for burning something in the datapack oven collide with the plugin?
I could remove the datapack and see if it works, but I think that's not the point, I don't know how to write plugins.

**Comment by espidev** [comment]
Okay, I've figured out that this is probably due to some sort of problematic crafting recipe on your server?

Let me know if this works, when you are ready: https://ci.espi.dev/job/ProtectionStones/lastSuccessfulBuild/artifact/target/protectionstones-2.6.9.jar

**Comment by espidev** [comment]
I added a check to ignore problematic recipes in that version of the plugin.

Yeah you might have some sort of custom crafting recipe causing errors when bukkit tries to load it

**Comment by OlekMK342** [comment]
I haven't removed the datapack but the plugin works!

Thank you very much, I really appreciate your help :)
I am extremely grateful to you.

**Comment by espidev** [comment]
Awesome!

The datapack might be an issue in the future possibly, so you may want to double check that.
The server is complaining that there is a crafting recipe that is just air
