### ISSUE TITLE
Bukkit support

### ISSUE THREAD

**Issue by viktorkovarik** [espidev/ProtectionStones#148]
Hey,
I was running this plugin ever since on my server and recently I decided to run my server on latest bukkit 1.15.2. Everything is working fine but your addon seems not tu support bukkit anymore.
Here is error log from server console:
`[23:18:15] [Server thread/INFO]: [ProtectionStones] Enabling ProtectionStones v2.6.9
[23:18:15] [Server thread/ERROR]: Error occurred while enabling ProtectionStones v2.6.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at dev.espi.protectionstones.FlagHandler.registerHandlers(FlagHandler.java:101) ~[?:?]
        at dev.espi.protectionstones.ProtectionStones.onEnable(ProtectionStones.java:437) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:344) [craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:448) [craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:374) [craftbukkit.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:448) [craftbukkit.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:254) [craftbukkit.jar:git-Bukkit-8160e29]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:762) [craftbukkit.jar:git-Bukkit-8160e29]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:146) ~[craftbukkit.jar:git-Bukkit-8160e29]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:92) ~[craftbukkit.jar:git-Bukkit-8160e29]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 11 more`
Thanks in advance for finding what is going on!

**Comment by espidev** [comment]
You need to use spigot, plain craftbukkit is not supported at all, and there is no reason to use it

**Comment by viktorkovarik** [comment]
Well this is the first time some plugin is not working with Bukkit anymore. I am now bit scared if plugins from bukkit will work correctly on spigot because it's quite different distribution... Hope it will.

**Comment by viktorkovarik** [comment]
Okay I've switched to Spigot and all my plugins seems to be working correctly.
Thank you for the tip!
