### ISSUE TITLE
Exception when placing PS

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#172]
`[08:53:34 ERROR]: Could not pass event BlockPlaceEvent to ProtectionStones v2.7.3
java.lang.NullPointerException: null
        at dev.espi.protectionstones.utils.WGUtils.getPlayerAdjacentRegionGroups(WGUtils.java:213) ~[?:?]
        at dev.espi.protectionstones.BlockHandler.createActualRegion(BlockHandler.java:224) ~[?:?]
        at dev.espi.protectionstones.BlockHandler.createPSRegion(BlockHandler.java:157) ~[?:?]
        at dev.espi.protectionstones.BlockHandler.createPSRegion(BlockHandler.java:103) ~[?:?]
        at dev.espi.protectionstones.ListenerClass.onBlockPlace(ListenerClass.java:80) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor511.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:332) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.ItemStack.placeItem(ItemStack.java:231) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:497) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[?:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-243]
`

ProtectionStones version 2.7.3
git-Paper-243 (MC: 1.14.4)

I am still investigating, probably related to non adjacent permission

**Comment by espidev** [comment]
Hmm, are there any regions that are of a block type that is not configured?

**Comment by Leonardo-Fiori** [comment]
Yup! It was. Removed old test bedrock regions and it started working. Now also non-adjacent limit works. Thanks.
