### ISSUE TITLE
Error al implementarlo

### ISSUE THREAD

**Issue by SoulDeveloperCompany** [espidev/ProtectionStones#186]
Buenas, intente implementar el plugin a mi servidor & me genero el siguiente error, ¿me podrian explicar que tengo mal?

[Server thread/ERROR]: Could not pass event PlayerJoinEvent to ProtectionStones v2.7.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-758abbe-2b00831]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.PlayerList.a(PlayerList.java:199) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.LoginListener.c(LoginListener.java:153) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.LoginListener.tick(LoginListener.java:52) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.NetworkManager.a(NetworkManager.java:219) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:128) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1126) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1007) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:846) ~[server.jar:git-Spigot-758abbe-2b00831]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-758abbe-2b00831]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: java.lang.NullPointerException
        at dev.espi.protectionstones.ListenerClass.onPlayerJoin(ListenerClass.java:62) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-758abbe-2b00831]
        ... 14 more

**Comment by espidev** [comment]
Update your spigot, or use paper.

**Comment by SoulDeveloperCompany** [comment]
I have everything with the latest version, what server do you use?

**Comment by espidev** [comment]
Do not use third party sites, they are out of date.

Please build spigot with the latest BuildTools: https://www.spigotmc.org/wiki/buildtools/
or
Use paper (recommended): https://papermc.io/downloads

**Comment by SoulDeveloperCompany** [comment]
it's for a 1.16 server
I have everything updated and I don't understand why I get that error

**Comment by espidev** [comment]
Where are you getting your updated spigot from?

**Comment by SoulDeveloperCompany** [comment]
of this page:
https://getbukkit.org/download/spigot

**Comment by espidev** [comment]
Do not use that site, they are completely out of date and not affiliated with spigot.

https://papermc.io/downloads

**Comment by SoulDeveloperCompany** [comment]
Thanks for your attention, I will try that right away
