### ISSUE TITLE
Console error when doing /ps admin flag piston null

### ISSUE THREAD

**Issue by Leonardo-Fiori** [espidev/ProtectionStones#20]
This error appeared in console when i tried to set to null the piston flag. Then i tried to set it to allow, and it did not work either:

[11:10:36 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ps admin flag World piston null' in dev.espi.ProtectionStones.PSCommand(ps)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.2.jar:git-Paper-97]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1832) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1640) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-97]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.14.2.jar:git-Paper-97]
        at com.sk89q.worldguard.protection.regions.ProtectedRegion.setFlag(ProtectedRegion.java:432) ~[?:?]
        at dev.espi.ProtectionStones.commands.ArgFlag.setFlag(ArgFlag.java:97) ~[?:?]
        at dev.espi.ProtectionStones.commands.ArgAdminFlag.argumentAdminFlag(ArgAdminFlag.java:54) ~[?:?]
        at dev.espi.ProtectionStones.commands.ArgAdmin.executeArgument(ArgAdmin.java:77) ~[?:?]
        at dev.espi.ProtectionStones.PSCommand.execute(PSCommand.java:64) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-97]
        ... 16 more
[11:10:49 INFO]: <logan_1_eye> Pay what zdavidMeson.
[11:10:51 INFO]: NemesiS_ITA issued server command: /ps admin flag World piston allow
[11:10:51 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ps admin flag World piston allow' in dev.espi.ProtectionStones.PSCommand(ps)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.14.2.jar:git-Paper-97]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:736) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1832) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1640) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:976) ~[patched_1.14.2.jar:git-Paper-97]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-97]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at dev.espi.ProtectionStones.commands.ArgFlag.setFlag(ArgFlag.java:102) ~[?:?]
        at dev.espi.ProtectionStones.commands.ArgAdminFlag.argumentAdminFlag(ArgAdminFlag.java:54) ~[?:?]
        at dev.espi.ProtectionStones.commands.ArgAdmin.executeArgument(ArgAdmin.java:77) ~[?:?]
        at dev.espi.ProtectionStones.PSCommand.execute(PSCommand.java:64) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.2.jar:git-Paper-97]
        ... 16 more

**Comment by Leonardo-Fiori** [comment]
Sorry, i was just writing piston instead of pistons, i think because the original WG flag is called piston, not pistons. Doing the command with pistons will work.
