### ISSUE TITLE
An internal error when selling to `null` produce an error

### ISSUE THREAD

**Issue by Shiikii** [espidev/ProtectionStones#203]
1) Create region
2) use /ps sell command
3) use /ps removeowner (in attempt to let pple buy "from system")
4) check if work, by using /ps buy
5) https://i.imgur.com/X9zYf6z.png

Console:
```javascript
[00:21:27] [Server thread/INFO]: Mil3s_ issued server command: /ps get 11x11
[00:21:44] [Server thread/INFO]: Mil3s_ issued server command: /ps sell 1000
[00:21:50] [Server thread/INFO]: Mil3s_ issued server command: /ps removeowner Mil3s_
[00:21:53] [Server thread/INFO]: Mil3s_ issued server command: /ps buy
[00:21:53] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing "ps buy" in dev.espi.protectionstones.PSCommand(ps)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:156) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1497) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
at java.lang.String.replace(String.java:2240) ~[?:1.8.0_121]
at dev.espi.protectionstones.commands.ArgBuySell.executeArgument(ArgBuySell.java:92) ~[?:?]
at dev.espi.protectionstones.PSCommand.execute(PSCommand.java:127) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.15.2.jar:git-Spigot-800b93f-a0e88fb]
... 16 more```

**Comment by espidev** [comment]
I think it's best to add a way to sell a region from the system rather than needing this hacky way. Thanks for the bug report about this case.
