### ISSUE TITLE
com.electronwill.nightconfig.core.io.ParsingException: Invalid separator '"' in array.

### ISSUE THREAD

**Issue by TiziFioretti** [espidev/ProtectionStones#204]
[05:44:02] [Server thread/ERROR]: Error occurred while enabling ProtectionStones v2.7.6 (Is it up to date?)
com.electronwill.nightconfig.core.io.ParsingException: Invalid separator '"' in array.
        at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:38) ~[?:?]
        at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:32) ~[?:?]
        at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:68) ~[?:?]
        at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[?:?]
        at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:101) ~[?:?]
        at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:88) ~[?:?]
        at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[?:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[?:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[?:?]
        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[?:?]
        at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[?:?]
        at com.electronwill.nightconfig.core.file.SimpleCommentedFileConfig.load(SimpleCommentedFileConfig.java:38) ~[?:?]
        at dev.espi.protectionstones.PSConfig.initConfig(PSConfig.java:159) ~[?:?]
        at dev.espi.protectionstones.ProtectionStones.loadConfig(ProtectionStones.java:405) ~[?:?]
        at dev.espi.protectionstones.ProtectionStones.onEnable(ProtectionStones.java:493) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:493) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:407) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-9639cf7-4b9bc9d]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by espidev** [comment]
Try pasting your config here to check for errors: https://www.toml-lint.com/

**Comment by espidev** [comment]
no response
