### ISSUE TITLE
/ps home -> error 

### ISSUE THREAD

**Issue by shaqupl** [espidev/ProtectionStones#250]
[13:28:12 WARN]: [ProtectionStones] Plugin ProtectionStones v2.8.0 generated an exception while executing task 5364742
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[patched_1.16.5.jar:git-Paper-567]
        at com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:121) ~[?:?]
        at dev.espi.protectionstones.utils.WGUtils.getRegionManagerWithWorld(WGUtils.java:57) ~[?:?]
        at dev.espi.protectionstones.PSPlayer.lambda$getPSRegions$3(PSPlayer.java:323) ~[?:?]
        at java.util.HashMap.forEach(HashMap.java:1336) ~[?:?]
        at dev.espi.protectionstones.PSPlayer.getPSRegions(PSPlayer.java:321) ~[?:?]
        at dev.espi.protectionstones.PSPlayer.getHomes(PSPlayer.java:350) ~[?:?]
        at dev.espi.protectionstones.commands.ArgHome.openHomeGUI(ArgHome.java:94) ~[?:?]
        at dev.espi.protectionstones.commands.ArgHome.lambda$executeArgument$1(ArgHome.java:134) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-567]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-567]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-567]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]

[13:30:42 INFO]: ProtectionStones: 2.8.0
[13:30:42 INFO]: Developers: [EspiDev]
[13:30:42 INFO]: Bukkit:  git-Paper-567 (MC: 1.16.5)
[13:30:42 INFO]: WG: 7.0.4+f7ff984

**Comment by espidev** [comment]
Could you try this version to see if it fixes your issue: https://ci.espi.dev/job/ProtectionStones/331/

**Comment by espidev** [comment]
Should be fixed in 2.8.1
