### ISSUE TITLE
Generating ghost regions 1.17+ Java 16

### ISSUE THREAD

**Issue by CroaBeast** [espidev/ProtectionStones#275]
Hi, I reported on your Discord that issue in the title.
Basically, when I create a region using protection stones below y = 0, it works fine the first time it places, but when it breaks, it shows this error and the region can't be deleted totally. It becomes hidden.
After unhidding it using /ps admin unhide, I can see the block again, but when it breaks that time, the same issue happens.
Server: Purpur-1.17-1255
Java Version: 16
PS Version: 2.8.5
WG Version: [Last dev-build](https://builds.enginehub.org/job/worldguard/18261) (Also I asked support in the WG discord but they say this issue is generated by ProtectionStones)
Error:
```>.... [00:36:51 ERROR]: Could not pass event BlockBreakEvent to ProtectionStones v2.8.5
java.lang.NullPointerException: Cannot invoke "dev.espi.protectionstones.PSRegion.getTypeOptions()" because "r" is null
at dev.espi.protectionstones.ListenerClass.playerBreakProtection(ListenerClass.java:98) ~[?:?]
at dev.espi.protectionstones.ListenerClass.onBlockBreak(ListenerClass.java:186) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor565.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.jar:git-Purpur-1255]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.jar:git-Purpur-1255]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.jar:git-Purpur-1255]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.jar:git-Purpur-1255]
at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:401) ~[?:?]
at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:355) ~[?:?]
at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:315) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1807) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.jar:git-Purpur-1255]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1414) ~[patched_1.17.jar:git-Purpur-1255]
at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[patched_1.17.jar:git-Purpur-1255]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1392) ~[patched_1.17.jar:git-Purpur-1255]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1385) ~[patched_1.17.jar:git-Purpur-1255]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1361) ~[patched_1.17.jar:git-Purpur-1255]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1272) ~[patched_1.17.jar:git-Purpur-1255]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[patched_1.17.jar:git-Purpur-1255]
at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by espidev** [comment]
**high priority, blocker for 1.18**

**Comment by CroaBeast** [comment]
Little reminder: Merging protections cause to lose all other protection stones and hiding the region and the blocks.
Unable to locate it using /ps info or /rg info, but it can be found using /rg list

Both issues causes to not use another protection stone to protect again the ghost region.

**Comment by espidev** [comment]
> Little reminder: Merging protections cause to lose all other protection stones and hiding the region and the blocks.
> Unable to locate it using /ps info or /rg info, but it can be found using /rg list
> 
> Both issues causes to not use another protection stone to protect again the ghost region.

I just tested today but I'm not actually able to duplicate the issue, could you please give me your block config?

**Comment by espidev** [comment]
Could you please try again with the latest version of paper, worldguard, and worldedit dev builds? I used to have this issue when testing a few weeks ago, but not after upgrading to the latest versions it seems....

**Comment by CroaBeast** [comment]
Oh, I just try it with the last dev builds and merging was solved, but not using protection stones below y = 0.

**Comment by espidev** [comment]
Please try this build: https://ci.espi.dev/job/ProtectionStones/373/

Set radiusY to -1. This should support negative y-levels (I also updated to native 1.17, newest WG/WE, removing 1.13-1.16 compatibility)

**Comment by CroaBeast** [comment]
Now it works, and merging regions below y = 0 also works.
So, the issue is solved :D

**Comment by espidev** [comment]
Nice, I'll need to add a converter as well once I have time before release so that old 0-256 regions will be updated as well.

In the end I guess the bug was either some Spigot, WG or WE issue?
