### ISSUE TITLE
WorldGuard error with protectionstones, dont know how to fix

### ISSUE THREAD

**Issue by rackgaming** [espidev/ProtectionStones#354]
```
[14:09:13 WARN]: java.lang.IllegalStateException: New flags cannot be registered at this time
[14:09:13 WARN]: 	at worldguard-bukkit-7.0.8-beta-01-dist.jar//com.sk89q.worldguard.protection.flags.registry.SimpleFlagRegistry.register(SimpleFlagRegistry.java:60)
[14:09:13 WARN]: 	at ProtectionStones-2.10.3.jar//dev.espi.protectionstones.FlagHandler.registerFlags(FlagHandler.java:69)
[14:09:13 WARN]: 	at ProtectionStones-2.10.3.jar//dev.espi.protectionstones.ProtectionStones.onLoad(ProtectionStones.java:547)
[14:09:13 WARN]: 	at PluginManager.jar//net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:243)
[14:09:13 WARN]: 	at PluginManager.jar//net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:198)
[14:09:13 WARN]: 	at PluginManager.jar//net.lenni0451.spm.commands.subs.Reload_Sub.execute(Reload_Sub.java:38)
[14:09:13 WARN]: 	at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94)
[14:09:13 WARN]: 	at PluginManager.jar//net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110)
[14:09:13 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[14:09:13 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[14:09:13 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[14:09:13 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:872)
[14:09:13 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:473)
[14:09:13 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[14:09:13 WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[14:09:13 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1188)
[14:09:13 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303)
[14:09:13 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rackgaming** [comment]
[https://worldguard.enginehub.org/en/latest/developer/regions/custom-flags/](url)

**Comment by espidev** [comment]
Weird, did the plugin start properly? Do you have an up to date worldguard?
