### ISSUE TITLE
console error in start server

### ISSUE THREAD

**Issue by Dancbeunny98** [espidev/ProtectionStones#49]
```
> [14:22:48] [Server thread/INFO]: [ProtectionStones] Enabling ProtectionStones v2.2.1
> [14:22:48] [Server thread/INFO]: Protection Stone Blocks:
> [14:22:48] [Server thread/INFO]: - DIAMOND_BLOCK (DIAMOND_BLOCK)
> [14:22:48] [Server thread/INFO]: Error parsing flag: use
Error:
> [14:22:48] [Server thread/WARN]: com.sk89q.worldguard.protection.flags.InvalidFlagFormat: Expected none/allow/deny but got 'false'
> [14:22:48] [Server thread/WARN]: at com.sk89q.worldguard.protection.flags.StateFlag.parseInput(StateFlag.java:91)
> [14:22:48] [Server thread/WARN]: at com.sk89q.worldguard.protection.flags.StateFlag.parseInput(StateFlag.java:28)
> [14:22:48] [Server thread/WARN]: at dev.espi.protectionstones.FlagHandler.initDefaultFlagsForBlock(FlagHandler.java:89)
> [14:22:48] [Server thread/WARN]: at dev.espi.protectionstones.PSConfig.initConfig(PSConfig.java:182)
> [14:22:48] [Server thread/WARN]: at dev.espi.protectionstones.ProtectionStones.loadConfig(ProtectionStones.java:391)
> [14:22:48] [Server thread/WARN]: at dev.espi.protectionstones.ProtectionStones.onEnable(ProtectionStones.java:461)
> [14:22:48] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [14:22:48] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
> [14:22:48] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
> [14:22:48] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
> [14:22:48] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
> [14:22:48] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
> [14:22:48] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266)
> [14:22:48] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
> [14:22:48] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
> [14:22:48] [Server thread/INFO]: - GOLD_BLOCK (GOLD_BLOCK)
> [14:22:48] [Server thread/INFO]: Error parsing flag: use
Error:
> [14:22:48] [Server thread/WARN]: com.sk89q.worldguard.protection.flags.InvalidFlagFormat: Expected none/allow/deny but got 'false'
> [14:22:48] [Server thread/WARN]: at com.sk89q.worldguard.protection.flags.StateFlag.parseInput(StateFlag.java:91)
> [14:22:48] [Server thread/WARN]: at com.sk89q.worldguard.protection.flags.StateFlag.parseInput(StateFlag.java:28)
> [14:22:48] [Server thread/WARN]: at dev.espi.protectionstones.FlagHandler.initDefaultFlagsForBlock(FlagHandler.java:89)
> [14:22:48] [Server thread/WARN]: at dev.espi.protectionstones.PSConfig.initConfig(PSConfig.java:182)
> [14:22:48] [Server thread/WARN]: at dev.espi.protectionstones.ProtectionStones.loadConfig(ProtectionStones.java:391)
> [14:22:48] [Server thread/WARN]: at dev.espi.protectionstones.ProtectionStones.onEnable(ProtectionStones.java:461)
> [14:22:48] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [14:22:48] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
> [14:22:48] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
> [14:22:48] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461)
> [14:22:48] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375)
> [14:22:48] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449)
> [14:22:48] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266)
> [14:22:48] [Server thread/WARN]: at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
> [14:22:48] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by espidev** [comment]
As it says, you can't use true/false for flags, you have to use allow/deny/none
